apiVersion: v1
kind: Service
metadata:
  name: thymeleaf-service
  labels:
    app: thymeleaf-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: thymeleaf-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thymeleaf-app
  name: thymeleaf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thymeleaf-app
  template:
    metadata:
      labels:
        app: thymeleaf-app
    spec:
      containers:
        - image: simoganger/sample-k8s-project:1.0.0
          imagePullPolicy: Always
          name: sample-k8s-project
          ports:
            - containerPort: 8080




